Add kamban pipeline file, testing 4... Refs (#172)

diff --git a/.github/workflows/keywordKamban.yml b/.github/workflows/keywordKamban.yml
--- a/.github/workflows/keywordKamban.yml
+++ b/.github/workflows/keywordKamban.yml
@@ -27,6 +27,15 @@ jobs:
             echo "found=false" >> $GITHUB_OUTPUT
           fi
 
+      - name: Verificar si el Secret existe
+        run: |
+          if [ -z "${{ secrets.GH_PAT }}" ]; then
+            echo "❌ ERROR: El secret GH_PAT está vacío o no se encuentra."
+            exit 1
+          else
+            echo "✅ El secret GH_PAT tiene contenido."
+          fi
+          
       - name: Obtener node ID del issue
         if: steps.parse.outputs.found == 'true'
         id: issue_node
